title = 'Explore Miño'

contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'

copyright = 'All rights reserved'

weight = 1

[params]
    author = 'Brendo Labs'
    description = 'Developed by Brendo Labs'